version: '2'
services:
  openlmis:
    image: "lmistrainingapp/openlmis-localised"
    ports:
      - "8080:8080"
      - "8877:8877"
    env_file:
      - ./db.env
    links:
      - trainingdb
  trainingdb:
    image: "postgres:9.4"
    env_file:
      - ./db.env
